DFS/BFS/Dijkstra and Travis.
alexey-kotlyar/algostructure pull request #7
Opened 2017-05-17 13:32 UTC by AVParamonov

DFS/BFS/Dijkstra search algorithms implementations added.
Travis config added.

2017-05-18 17:55 UTC, zfrgt requested changes
Please see comments

2017-05-23 16:26 UTC, zfrgt requested changes
comments

2017-05-23 16:26 UTC, alexey-kotlyar commented on algorithms/src/main/java/com/aparamonov/algostructure/search/BFS.java
> +        List<Node<T>> visited = new ArrayList<>();
i'm not really sure this change is necessary. you're working with *graph* structures, not arrays. please check the performance for linked and array-lists

2017-05-24 14:55 UTC, AVParamonov commented on algorithms/src/main/java/com/aparamonov/algostructure/search/BFS.java
> +        List<Node<T>> visited = new ArrayList<>();
Measured performance difference between those two variants and it seems that it is not significant if exists at all cause we use them in streams.

2017-05-25 09:44 UTC, AVParamonov commented
@alexey-kotlyar please review.

2017-05-25 10:13 UTC, alexey-kotlyar commented
@AVParamonov gj, will merge it now. one more point for practice - plz add the tests' results to the readme.md of the repository in table format

2017-05-25 10:13 UTC, merged